# File: Pulsar/system_config.yaml

version: 1
validSensors:
  - input:temperature
  - input:humidity
  - temperature_f
  - temperature_c
  - humidity
  - pressure
  - humidity_status
  - comfort_score
cycleTime: 100
redis:
  endpoints:
    - localhost:6379
  poolSize: 8
  retryCount: 3
  retryBaseDelayMs: 100
  connectTimeout: 5000
  syncTimeout: 1000
  keepAlive: 60
  password: null
  ssl: false
  allowAdmin: false
bufferCapacity: 100
